products-styles:
  css:
    theme:
      css/products.css: {}
      'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css': { type: external }
      # If you want to reuse CSS from another module, add it like this:
      # ../other_module/css/banner.css: {}
  js:
    js/products.js: {}
    'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js': { type: external }
  dependencies:
    - core/jquery
    - core/drupal
    - bim_landing/bim-landing-page